config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :photos
  root "photos#index"

  resources :users

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :photos, only: [:index, :create, :show, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
	mount_uploader :file_location, PhotoImageUploader
	validates_presence_of :title, :date, :description, :file_location
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/photos_controller.rb
class Api::V1::PhotosController < ApiController

  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find_by(params[:id])
    if !@photo
      render json: {
        message: "Can't find the photo!",
        status: 400
      }
    else
      render "api/v1/photos/show"
    end
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      render json: {
        message: "Photo created successfully!",
        result: @photo
      }
    else
      render json: {
        errors: @photo.errors
      }
    end
  end

  def update
    @photo = Photo.find_by(params[:id])
    if @photo.update(photo_params)
      render json: {
        message: "Photo updated successfully!",
        result: @photo
      }
    else render json: {
      errors: @photo.errors
    }
    end
  end

  def destroy
    @photo = Photo.find_by(params[:id])
    @photo.destroy
      render json: {
        message: "Photo destroy successfully!"
      }
  end


  private

  def photo_params
    params.permit(:title, :date, :description, :file_location)
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :age, :region, :phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :gender, :region, :age, :phone])
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	before_action :set_photo, :only => [:show, :edit, :update, :destroy]

	def index
		@photos = Photo.all
	end

	def new
		@photo = Photo.new
	end

	def create
		@photo = Photo.new(photo_params)
		if @photo.save
			redirect_to photos_url
		else
			render :action => :new
		end
	end

	def update
		if @photo.update_attributes(photo_params)
			redirect_to photo_path(@photo)
		else
			render :action => :edit
		end
	end

	def destroy
		@photo.destroy

		redirect_to photos_url
	end

	private

	def set_photo
		@photo = Photo.find(params[:id])
	end

	def photo_params
		params.require(:photo).permit(:title, :date, :description, :file_location)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
  
end

app/helpers/api/v1/photos_helper.rb
module Api::V1::PhotosHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoAlbum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expaded="false">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "My family album", root_path, class: "navbar-brand"%>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to 'All User', users_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
              <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
              <li><%= link_to('Log out', destroy_user_session_path, method: :delete)%></li>
              <li><%= link_to('Edit Profile', edit_user_registration_path) %></li>
              <% else %>
              <li><%= link_to('Sign up', new_user_registration_path) %></li>
              <li><%= link_to('Log in', new_user_session_path) %>
              <% end %>
            </ul>
          </div>


        </div> <!-- containner-fluid -->
      </nav>

      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert"><%= notice %></div>
      <% elsif flash[:alert] %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<% if @photo.errors.present? %>
	<ul>
		<% @photo.errors.each do |error, message| %>
		<li><%= "#{error.capitalize} #{message}" %></li>
		<% end %>
	</ul>
<% end%>

<div class="form">
	<%= form_for @photo do |f|%>
		<div class="form-group">
			<%= f.label :title, "Title" %>
			<%= f.text_field :title %>
		</div>

		<div class="form-group">
			<%= f.label :date, "Date" %>
			<%= f.text_field :date %>
		</div>

		<div class="form-group">
			<%= f.label :description, "Description" %>
			<%= f.text_area :description %>
		</div>

		<div class="form-group">
			<%= f.label :file_location, "File Location" %>
			<%= f.file_field :file_location %>
		</div>

		<%= f.submit %>
	<% end %>
</div>

app/views/photos/edit.html.erb
<%= render :partial => "form" %>

app/views/photos/index.html.erb
<table class="table">
	<% @photos.each do |photo| %>
		<tr>
			<td><%= photo.title %></td>
			<td><%= link_to 'Show', photo_path(photo) %></td>
			<td><%= link_to 'Edit', edit_photo_path(photo) %></td>
			<td><%= link_to 'Destroy', photo_path(photo), method: :delete, data:{ confirm: "Are you sure?"} %></td>
		</tr>
	<% end %>
</table>


<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<%= render :partial => "form" %>

app/views/photos/show.html.erb
<%= @photo.title %>
<%= @photo.date %>
<%= image_tag @photo.file_location.url, size: "140x140", class: "img-thumbnail" %>
<%= simple_format(@photo.description) %>

<%= link_to 'Back to index', photos_path %>

app/views/users/index.html.erb
<h1>All User</h1>

<table class="table">
  <tr>
    <th>Avatar</th>
    <th>Name</th>
    <th>Email</th>
    <th>Gender</th>
    <th>Age</th>
    <th>Region</th>
    <th>Phone</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.avatar if user.avatar? %></td>
      <td><%= user.name%></td>
      <td><%= user.email%></td>
      <td><%= user.gender%></td>
      <td><%= user.age%></td>
      <td><%= user.region%></td>
      <td><%= user.phone%></td>
    </tr>
  <% end %>
</table>